### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by plainyuan** [open-source-translation/celery-cn#18]
日志：Logging 模块，最下方警告处，有一个错别字:
_，在本案例中使用**性用卡号**对实际的号码进行加密，并且进行安全存储，然后在任务中进行检索解密。_ 
应该是信用卡号

**Comment by 0nise** [comment]
已更正，感谢反馈

**Comment by plainyuan** [comment]
不客气啦，俺也是查文档时注意到的。感谢作者翻译~~~

r4v3zn <notifications@github.com> 于2020年8月14日周五 下午4:37写道：
